repos:
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        files: 'asyncio_guard/.*'
        stages:
        - commit
        - push
      - id: isort
        files: 'tests/.*'
        stages:
        - commit
        - push
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.7.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
        files: 'asyncio_guard'
        stages:
        - commit
        - push
    -   id: autopep8
        files: 'tests'
        stages:
        - commit
        - push
