name: Test package

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_ci.txt

    - name: Lint with pre-commit config
      run: pre-commit run --all-files

    - name: Test with mypy
      run: mypy -m asyncio_guard 

    - name: Test with pytest
      env:
        PYTHONPATH: .
      run: pytest --asyncio-mode=auto .

